version: '3'

services:
  api:
    build: 
      context: ./api
      dockerfile: dockerfile-dev
    networks:
      - web_api
    ports:
      - "81:8080"
    volumes:
      - ./api:/usr/src/app

  web:
    build: 
      context: ./web
      dockerfile: dockerfile-dev
    ports:
      - "80:3000"
    networks:
      - web_api
    volumes:
      - ./web:/app

networks:
  web_api:
    driver: "bridge"