version: '3'

services:
  api:
    build: ./server
#    volumes:
#      - /sys:/sys
    
    command: ["python", '-m', 'server']
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server
    ports:
      - "8080:3000"