version: '3'

services:
  api:
    build: ./api
#    volumes:
#      - /sys:/sys
    networks:
      - web_api

  #web:
  #  build: ./web
  #  ports:
  #    - "8080:3000"
  #  networks:
  #    - web_api

networks:
  web_api:
    driver: "bridge"