FROM python:3.9

RUN mkdir -p /usr/src/server
WORKDIR /usr/src/server

COPY requirements.txt /usr/src/server
RUN pip install -r requirements.txt

RUN ls
COPY . /usr/src/server
WORKDIR /usr/src/server
RUN mkdir /usr/src/data


EXPOSE 5000
ENTRYPOINT ["sh", "/usr/src/server/start_gunicorn.sh"]