FROM python:3.10.4-buster

WORKDIR /usr/src/app

RUN apt-get -y update && apt-get -y upgrade \
&& apt-get install build-essential 
# runtime setup


ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /usr/lib/python3/dist-packages


COPY . /api
WORKDIR /api
RUN python -m pip install -r requirements.txt

ENTRYPOINT ["sh", "/api/start_gunicorn.sh"]