FROM arm32v7/python:3.10.4-buster

WORKDIR /usr/src/app

RUN apt-get -y update && apt-get -y upgrade \
&& apt-get install build-essential cron python3-dev python3-rpi.gpio -y
# runtime setup
ARG VERSION
ENV DOCKER_RPI_GPIO_VERSION ${VERSION}

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /usr/lib/python3/dist-packages


COPY . /api
WORKDIR /api
RUN python -m pip install -r requirements.txt

ENTRYPOINT ["sh", "/api/start_gunicorn.sh"]