# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [ push ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          working-directory: ./react-webapp
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          working-directory: ./react-webapp
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          working-directory: ./react-webapp
          cmd: test # wi
      
      
